Yongin/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('introduction/', include('introduction.urls')),
    path('', views.main, name="main"),
    path('posts/', include('posts.urls')),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

introduction/urls.py
from django.urls import path
from . import views

app_name="introduction"
urlpatterns = [
    path('',views.home, name="home"),
    path('activity/', views.activity, name="activity"),
    path('delicious/', views.delicious, name="delicious"),
    path('photo/', views.photo, name="photo"),
]

posts/urls.py
from django.urls import path
from .views import *

app_name="posts"
urlpatterns = [
    path('new/',new, name="new"),
    path('create/', create, name="create"),
    path('', main, name="main"),
    path('show/<int:post_id>/', show, name="show"), 
    path('update/<int:id>/', update, name="update"),
    path('delete/<int:id>/', delete, name="delete"),
    path('<int:post_id>/create_comment', create_comment, name="create_comment"),
    path('<int:comment_id>/update_comment', update_comment, name="update_comment"),
    path('<int:comment_id>/delete_comment', delete_comment, name="delete_comment"),
    path('<int:post_id>/post_like', post_like, name="post_like"),
    path('like_list/', like_list, name="like_list"),
]

introduction/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50, null=False)
    content = models.TextField()
    view_count = models.IntegerField(default=0) 
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    image = models.ImageField(upload_to= 'images/', null=True)
    user = models.ForeignKey(User, on_delete = models.CASCADE, null=True)
    like_user_set = models.ManyToManyField(User, blank=True, related_name='like_user_set', through='Like')

    @property
    def like_count(self):
        return self.like_user_set.count()

class Comment(models.Model):
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete = models.CASCADE)
    post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name = 'comments')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (('user','post'))

posts/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'image',
        ]
        labels = {
            'title': ('제목'),
            'content': ('내용'),
            'image': ('이미지'),
        }
        help_texts = {
            'title': ('제목을 입력해주세요.'),
            'content': ('내용을 입력해주세요.'),
        }


    def save(self, **kwargs):
        post = super().save(commit=False)
        post.user = kwargs.get('user', None)
        post.save()
        return post

Yongin/views.py
from django.shortcuts import render

def main(request):
    return render(request, 'main.html')

introduction/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'introduction/home.html')

def activity(request):
    return render(request, 'introduction/activity.html')

def delicious(request) :
    return render(request, 'introduction/delicious.html')

def photo(request) :
    return render(request, 'introduction/photo.html')

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.contrib.auth.decorators import login_required
from .forms import PostForm

# Create your views here.
def new(request):
    return render(request, 'posts/new.html')

@login_required
def create(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save(user = request.user)
            return redirect('posts:main')
        else : 
            form = PostForm()
            return render(request, 'posts/new.html', {'form':form})

def main(request):
    posts = Post.objects.all().order_by('-created_at')
    return render(request, 'posts/main.html', {'posts': posts})

def show(request, post_id):
    post = Post.objects.get(pk=post_id)
    post.view_count += 1
    post.save()
    all_comments = post.comments.all().order_by('-created_at')
    return render(request, 'posts/show.html', {'post':post, 'comments':all_comments})

def update(request, id):
    post = get_object_or_404(Post, pk=id)
    if request.method == "POST":
        post.title = request.POST['title']
        post.content = request.POST['content']
        post.image = request.FILES.get('image')
        post.save()
        return redirect('posts:show', post.id)
    return render(request, 'posts/update.html', {"post":post})

def delete(request, id):
    post = get_object_or_404(Post, pk=id)
    post.delete()
    return redirect("posts:main")

def create_comment(request, post_id):
    if request.method == "POST" :
        post = get_object_or_404(Post, pk=post_id)
        current_user = request.user 
        comment_content = request.POST.get('content')
        Comment.objects.create(content=comment_content, writer=current_user, post=post)
    return redirect('posts:show', post_id)

def update_comment(request, comment_id):
    comment=get_object_or_404(Comment, pk=comment_id)
    if request.method == "POST":
        post_id = comment.post.id
        comment.content=request.POST.get('content')
        comment.save()
        return redirect('posts:show', post_id)
    return render(request, 'posts/update_comment.html',{"comment":comment})

def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    post_id = comment.post.id
    comment.delete()
    return redirect('posts:show', post_id)

@login_required
def post_like(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.user in post.like_user_set.all():
        post.like_user_set.remove(request.user)
    else:
        post.like_user_set.add(request.user)
    
    if request.GET.get('redirect_to')=='show':
        return redirect('posts:show', post_id)
    else:
        return redirect('posts:main')

@login_required
def like_list(request):
    likes = request.user.like_set.all()
    return render(request, 'posts/like_list.html',{'likes':likes})

Yongin/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href = "{% static 'css/project.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Single+Day&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>
    <title>Beautiful City</title>
  </head>
  <body>
  
      {% block content %}
      {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

Yongin/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'shared/_navbar.html' %}
<img src="{% static 'images/용인시 로고.png' %}" width = "300"alt="용인시 로고" style="margin-top:50px;">
<h2 style="margin-top:20px; margin-left: 70px;">용인시 로고</h2> 
<img src="{% static 'images/용인시 지도.png' %}" width = "300"alt="용인시 지도" style="margin-top:50px; margin-left:20px;">
<h2 style="margin-top:20px; margin-left: 70px;">용인시 지도</h2> 
<img src="{% static 'images/마스코트.gif' %}" width = "300"alt="용인시 마스코트" style="margin-top:50px;">
<h2 style="margin-top:20px; margin-left: 70px;">용인시 마스코트</h2> 

{% endblock %}

Yongin/templates/shared/_navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/project.css' %}">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'main' %}" >아름다운 도시 용인</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'introduction:home' %}">용인에 대해 알아보기</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            용인에서 뭐하지?
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'introduction:delicious' %}">맛있는 것 먹으러 가기</a>
            <a class="dropdown-item" href="{% url 'introduction:photo' %}">인생샷 찍으러 가기</a>
            <a class="dropdown-item" href="{% url 'introduction:activity' %}">액티비티 즐기러 가기 </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:main' %}">용인인의 추천!</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:like_list' %}">좋아요한 글♥!</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_logout' %}">로그아웃</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_change_password' %}">비밀번호 변경</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_login' %}">로그인</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_signup' %}">회원가입</a>
        </li>
        {% endif %}
      </ul>
    </div>
</nav>

introduction/templates/introduction/activity.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'shared/_navbar.html' %}
<h1> 용인에서 즐겁게 놀자! </h1>
<div>
    <img src="{% static 'images/바운스 트램폴린파크.jpg' %}" width = "180"alt="바운스 트램폴린 파크" style="margin-top:10px; margin-left:20px;">
    <span style="margin-top:10px;"><h5>#바운스 트램폴린 파크</h5></span>
    <span style="margin-top:40px;">
        <h7>추억의 트램폴린을 아이도 성인도 즐기자! </h7></span>
    <span style="margin-top:70px;">
        <h7>경기도 용인시 기흥구 동백죽전대로 15번길 6</h7></span>
    <span style="margin-left:20px; margin-top:100px;">
        <h7>매일 10:30 ~ 21:00</h7></span>
    <span style="margin-left:20px; margin-top:130px;">
        <h7>070-8858-6433</h7></span>
</div>
<div>
    <img src="{% static 'images/플로우 하우스.jpg' %}" width = "210"alt="플로우 하우스" style="margin-top:30px; margin-left:20px;">
    <span style="margin-left:20px; margin-top:30px;"><h5>#플로우 하우스</h5></span>
    <span style="margin-left:20px; margin-top:60px;">
        <h7>국내 최초! 실내 서핑을 즐겨보아요!</h7></span>
    <span style="margin-left:20px; margin-top:90px;">
        <h7>경기도 용인시 기흥구 신고매로 124 롯데프리미엄아울렛기흥점 지하 2층</h7></span>
    <span style="margin-left:20px; margin-top:120px;">
        <h7>매일 11:00 ~ 20:30, 설날, 추석당일 휴무</h7></span>
    <span style="margin-left:20px; margin-top:150px;">
        <h7>031-8036-3042</h7></span>
</div>
<div>
    <img src="{% static 'images/플라이 스테이션.jpg' %}" width = "220"alt="플라이 스테이션" style="margin-top:30px; margin-left:20px;">
    <span style="margin-top:30px;"><h5>#플라이 스테이션</h5></span>
    <span style="margin-top:60px;">
        <h7>스카이다이빙을 실내에서 즐기자! </h7></span>
    <span style="margin-top:90px;">
        <h7>경기도 용인시 처인구 포곡읍 성산로 521</h7></span>
    <span style="margin-top:120px;">
        <h7>평일 10:30 ~ 20:00</h7></span>
    <span style="margin-top:150px;">
        <h7>031-1855-3946</h7></span>
</div>
{% endblock %}

introduction/templates/introduction/delicious.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'shared/_navbar.html' %}
<h1> 용인에서 뭐 먹지? </h1>
<h3>용인 중앙시장에서 먹기</h3>
<div>
    <img src="{% static 'images/빈대떡일번지.jpg' %}" width = "150"alt="빈대떡일번지" style="margin-top:10px; margin-left:20px;">
    <span style="margin-top:10px;"><h5>#빈대떡 일번지</h5></span>
    <span style="margin-top:60px;">
        <h7>비오는 날엔 막걸리에 빈대떡!</h7></span>
    <span style="margin-top:90px;">
        <h7>빈대떡 외에도 제육볶음, 동태전, 메밀전병 등 다양한 전과 처인성 막걸리, 가평잣막걸리, 알밤막걸리 등 여러 막걸리를 마셔볼 수 있어><</h7></span>
    <span style="margin-top:120px;">
        <h7>031-332-2997</h7></span>
</div>

<div>
    <img src="{% static 'images/오동족발.jpg' %}" width = "150"alt="오동족발" style="margin-top:15px; margin-left:20px;">
    <span style="margin-top:15px;"><h5>#오동 족발</h5></span>
    <span style="margin-top:65px;">
        <h7>쫀득쫀득함과 부드러움을 함께 느낄 수 있는 족발!</h7></span>
    <span style="margin-top:95px;">
        <h7>양도 많고 막국수도 정말 맛있어! 매콤한 불족발이 인기><</h7></span>
    <span style="margin-top:125px;">
        <h7>031-338-8896</h7></span>
</div>

<div>
    <img src="{% static 'images/진순자 계란말이 김밥.jpg' %}" width = "150"alt="진순자 계란말이 김밥" style="margin-top:15px; margin-left:20px;">
    <span style="margin-top:15px;"><h5>#진순자 계란말이 김밥</h5></span>
    <span style="margin-top:65px;">
        <h7>계란말이가 돌돌 말려있는 김밥!</h7></span>
    <span style="margin-top:95px;">
        <h7>계란말이 김밥말고도 잔치국수 칼국수도 맛있어! 가성비 갑><</h7></span>
    <span style="margin-top:125px;">
        <h7>031-6368-4617</h7></span>
</div>

<h3 style="margin-top:80px;">대학교 근처 맛집</h3>
<div>
    <h3>-단국대 맛집-</h3>
    <img src="{% static 'images/단국대 맛집.jpg' %}" width = "200"alt="단국대 맛집" style="margin-top:10px; margin-left:20px;">
    <img src="{% static 'images/단국대 맛집2.jpg' %}" width = "200"alt="단국대 맛집" style="margin-top:10px; margin-left:20px;">
    <span style="margin-top:5px;"><h5>#해피덮 - 연어덮밥</h5></span>
    <span style="margin-top:30px;"><h5>#고수찜닭 - 당면찜닭</h5></span>
    <span style="margin-top:55px;"><h5>#사부 - 짜장면</h5></span>
    <span style="margin-top:80px;"><h5>#족타구나 - 마늘양념족발</h5></span>
    <span style="margin-top:105px;"><h5>#배꼽빵빵 즉석 떡볶이 - 야채떡볶이</h5></span>
    <span style="margin-top:130px;"><h5>#싱싱한 연어와 바삭한 새우 - 연어회덮밥</h5></span>
    <span style="margin-top:155px;"><h5>#그란데 - 빠네</h5></span>
    <span style="margin-top:180px;"><h5>#돼지집 - 수육튀김</h5></span>
</div>

<div>
    <h3>-명지대(자연캠퍼스) 맛집-</h3>
    <img src="{% static 'images/명지대 맛집.jpg' %}" width = "200"alt="명지대 맛집" style="margin-top:10px; margin-left:20px;">
    <img src="{% static 'images/명지대 맛집2.jpg' %}" width = "200"alt="명지대 맛집" style="margin-top:10px; margin-left:20px;">
    <span style="margin-top:5px;"><h5>#가온누리 - 삼겹살</h5></span>
    <span style="margin-top:30px;"><h5>#코델리아 - 상하이 파스타</h5></span>
    <span style="margin-top:55px;"><h5>#루나리치 - 마르게리타 피자</h5></span>
    <span style="margin-top:80px;"><h5>#마라순코우 - 마라탕</h5></span>
    <span style="margin-top:105px;"><h5>#스시환 - 연어초밥</h5></span>
    <span style="margin-top:130px;"><h5>#전곱 - 치즈곱창볶음</h5></span>
    <span style="margin-top:155px;"><h5>#이태리부엌 - 알리오올리오</h5></span>
    <span style="margin-top:180px;"><h5>#오영쪽갈비 - 치즈쪽갈비</h5></span>
</div>


<div>
    <h3>-경희대(글로벌 캠퍼스) 맛집-</h3>
    <img src="{% static 'images/경희대 맛집.jpg' %}" width = "200"alt="경희대 맛집" style="margin-top:10px; margin-left:20px;">
    <span style="margin-top:50px;"><h5>#홍호아 - 양지쌀국수</h5></span>
    <span style="margin-top:75px;"><h5>#미미카츠 - 치즈카츠</h5></span>
    <span style="margin-top:100px;"><h5>#키와마루아지 - 미라멘</h5></span>
    <span style="margin-top:125px;"><h5>#익스프레스피스타애피자 - 갈릭포테이토 피자</h5></span>
</div>

{% endblock %}

introduction/templates/introduction/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'shared/_navbar.html' %}
<h1> 용인에 대해서 알아볼까요? </h1>

<h4>용인은 경기도 중남부에 위치한 시로 현재 경기도에서 수원시와 고양시에 이어 인구 3위의 도시입니다.</h4>
<h4>용인시는 21세기 들어 한국에서 가장 급격하게 성장한 도시이자 급격하게 인구가 늘어난 도시입니다.</h4>
<h4>또한 유수의 관광도시이기도 하죠! 에버랜드, 캐리비안 베이, 한국민속촌, 양지파인리조트 등 전국적으로 유명한 레저, 관광시설의 덕, 전국 지방자치단체 중 관광객 1위 자리를 차지하고 있답니다.</h4>
<h4>인구는 2020년 06월 기준 107만 3,115명입니다.</h4>
<h4>그리고 면적은 591.33km^2이죠.</h4>
<h4>용인에는 맛있는 맛집, 놀거리 정말 많고 다양해요!</h4>
<h4>용인에 놀러오세요!!!</h4> 

<img class="Y" src="{% static 'images/에버랜드.jpg' %}" width = "400"alt="에버랜드">
<img class="Y"src="{% static 'images/테마파크.jpg' %}" width = "300"alt="농촌 테마파크">
<img class="Y"src="{% static 'images/아파트.jpg' %}" width = "300"alt="아파트사진">
<img class="Y"src="{% static 'images/축제.jpg' %}" width = "300"alt="축제">
{% endblock %}

posts/templates/posts/like_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'shared/_navbar.html' %}
<div class="container">
   {% if user.is_authenticated %}
       <h1>좋아요한 글 목록</h1>
       <div class="row">
           {% for like in likes %}
               <div class="col-md-4 col-12">
                   <div class="card" style="width: 18rem; margin-top: 20px;">
                       <div class="card-body">
                           <h5 class="card-title">{{ like.post.title }}</h5>
                           <h5> 조회수 : {{ like.post.view_count }}</h5>
                           <a href="{% url 'posts:show' like.post.id %}" class="btn btn-primary">상세보기</a>
                       </div>
                   </div>
               </div>
           {% endfor %}
       </div>
   {% else %}
       <h3>로그인 후 이용이 가능합니다.</h3>
       <a href="{% url 'account_login' %}" class="btn btn-warning">로그인</a>
       <a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>
   {% endif %}
</div>
{% endblock %}

posts/templates/posts/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if user.is_authenticated %} 
{% include 'shared/_navbar.html' %}
<div class="container">
    <h1>글 목록입니다.</h1>
    <a href="{% url 'posts:new'%}" class="btn btn-primary">글 작성하기</a>
    <div class="row">
        {% for post in posts %}
        <div class="col-md-4 col-12">
            <div class="card" style="width: 18rem; margin-top: 20px;">
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.content }}</p>
                    <p>{{ post.created_at }}</p>
                    <p>조회수 : {{post.view_count}}</p>
                    <a href="{% url 'posts:post_like' post.id %}">
                        {% if user in post.like_user_set.all %}
                             <i class="fas fa-heart"></i>
                         {% else %}
                             <i class="far fa-heart"></i>
                         {% endif %}
                    </a>
                    <a href="{% url 'posts:show' post.pk %}" class="btn btn-primary">상세보기</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
    <h3>로그인 후 이용이 가능합니다.</h3>
    <a href="{% url 'account_login' %}" class="btn btn-warning">로그인</a>
    <a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>

{% endif %}
{% endblock %}

posts/templates/posts/new.html
{% extends 'base.html' %}

{% block content %}
{% include 'shared/_navbar.html' %}
<div class="container">
    <h1>
        새로운 글 작성하기
    </h1>
    <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }} 
        <input type="submit" value="글 작성" class="btn btn-outline-primary">
    </form>
</div>
{% endblock %}

posts/templates/posts/show.html
{% extends 'base.html' %}
{% block content %}
{% include 'shared/_navbar.html' %}
    <h1>상세보기 페이지</h1>
    <h3>글 제목 : {{ post.title }} </h3><br>
    {% if post.user %}
        <h3>작성자 : {{post.user}}</h3><br>
    {% else %}
        <h3>작성자 : 알 수 없음</h3><br>
    {% endif %}
    <h3>글 내용 : {{ post.content }} </h3><br>
    <h3>작성 시각 : {{ post.created_at }} </h3><br>
    <h3>수정 시각 : {{ post.updated_at}} </h3><br>
    <h3> 조회수 : {{ post.view_count}}</h3><br>
    {% if post.image %}
    <img src = "{{post.image.url}}">
    {% endif %}
    {% if user == post.user %}
        <a href = "{% url 'posts:update' post.pk %}">수정하기</a>
        <a href = "{% url 'posts:delete' post.pk %}">삭제하기</a>
    {% endif %}
    <a href="{% url 'posts:post_like' post.id %}?redirect_to=show">
        {% if user in post.like_user_set.all %}
             <i class="fas fa-heart"></i>
         {% else %}
             <i class="far fa-heart"></i>
         {% endif %}
    </a>
    <div class="container mt-5">
        <form class="form-row" action="{% url 'posts:create_comment' post.id %}" method="POST">
          {% csrf_token %}
          <textarea class="form-control col-11 mr-2" name="content" placeholder="댓글 내용 입력..."></textarea>
          <input type="submit" class="btn btn-primary" value="확인">
        </form>
    </div>
    <div class="container mt-5 mb-5">
        {% for comment in comments %}
            <div class="card">
                <div class="card-body">
                    <b>{{ comment.writer }}</b> : {{ comment.content }}<br>
                    <small>{{ comment.created_at }}</small>
                    {% if user == comment.writer %}
                        <a href="{% url 'posts:update_comment' comment.id %}" class="btn btn-primary">댓글 수정</a>
						<a href="{% url 'posts:delete_comment' comment.id %}" class="btn btn-danger">댓글 삭제</a>
					{% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
 

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block content %}
{% include 'shared/_navbar.html' %}
<div class="container">
    <h1>
        수정하기
    </h1>
    <form action="{% url 'posts:update' post.id%}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label>글 제목</label>
            <input type="text" class="form-control" name="title" value="{{post.title}}">
        </div>
        <div class="form-group">
            <label>글 내용</label>
            <textarea class="form-control" name="content">{{post.content}}</textarea>
            <input type="file" name="image">
        </div>
        <input type="submit" value="글 수정" class="btn btn-outline-primary">
    </form>
</div>
{% endblock %}

posts/templates/posts/update_comment.html
{% extends 'base.html' %}

{% block content %}
<div class="container"> 
	<h1> 댓글 수정 </h1> 
	<form action="{% url 'posts:update_comment' comment.id %}" method="POST" enctype="multipart/form-data"> 
		{% csrf_token %} 
		 <div class="form-group">
			 <label>댓글 내용</label>
			 <textarea class="form-control" name="content"> {{ comment.content }} </textarea>
		 </div>
 		<input type="submit" value="댓글 수정" class="btn btn-outline-primary">
	 </form> 
</div>
{% endblock %}